version: '3.8'

services:
  # 1. Custom Express Application Microservice
  omnifeed-backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}